name: "CI Deep"

env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

on:
  schedule:
    - cron: "0 3 * * 0" # at 3:00am UTC every Sunday
  workflow_dispatch:
    inputs:
      unitFuzzRuns:
        default: '50000'
        description: "Unit: number of fuzz runs."
        required: false
      integrationFuzzRuns:
        default: '50000'
        description: "Integration: number of fuzz runs."
        required: false
      forkFuzzRuns:
        default: '1000'
        description: "Fork: number of fuzz runs."
        required: false

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@main"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@main"

  test-integration:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: ${{ fromJSON(inputs.integrationFuzzRuns || '50000') }}
      foundry-profile: "test-optimized"
      match-path: "tests/integration/**/*.sol"
      name: "Integration tests"

  test-fork:
    needs: ["lint", "build"]
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: ${{ fromJSON(inputs.forkFuzzRuns || '1000') }}
      foundry-profile: "test-optimized"
      match-path: "tests/fork/**/*.sol"
      name: "Fork tests"

  notify-on-failure:
    if: always()
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send Slack notification"
        if: failure() # Runs only if a failure occurs in any previous job
        uses: "rtCamp/action-slack-notify@v2"
        env:
          SLACK_CHANNEL: "#ci-notifications"
          SLACK_MESSAGE: "CI Workflow failed for ${{ github.repository }} on branch ${{ github.ref }} at job ${{ github.job }}."
          SLACK_USERNAME: "GitHub CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
