name: "CI Slither"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0" # at 3:00am UTC every Sunday

jobs:
  lint:
    uses: "sablier-labs/gha-utils/.github/workflows/evm-lint.yml@main"

  slither-analyze:
    uses: "sablier-labs/gha-utils/.github/workflows/slither-analyze.yml@main"
